[package]
name = "getters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "getters"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
quote = "1.0.26"
syn = "2.0.15"
