[package]
name = "complemento3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.4"

[[example]]
name = "clousure"
path = "examples/clousure/main.rs"
